# Welcome to Jekyll!
#
# This file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'.

# Site settings
# Variables defined here will be accessible in the templates via {{ site.myvariable }}.
title: ▲▲▲
email: aegrobbel@gmail.com
description: >-
  Personal webpage for programming, art, and creative content, powered by Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  abbygrbl
linkedin_username: abbygrobbel
instagram_username: abbygrbl.art


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# minima value
show_excerpts: true

exclude: ['node_modules']
header_pages:
  - pages/notes.md
  - pages/about.md

#custom frontmatter defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Abby Grobbel
  - scope:
      path: ""
      type: drafts
    values:
      layout: post
      author: Abby Grobbel
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author: Abby Grobbel

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
